CREATE TABLE Account (
    id SERIAL PRIMARY KEY,
    name VARCHAR (255) NOT NULL,
    balance DECIMAL NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

